/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Commission {
  'id' : bigint,
  'level' : bigint,
  'orderId' : bigint,
  'timestamp' : Time,
  'amount' : bigint,
  'associate' : Principal,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'orderDate' : Time,
  'productId' : bigint,
  'totalAmount' : bigint,
  'quantity' : bigint,
  'associate' : Principal,
}
export interface PayoutRequest {
  'id' : bigint,
  'status' : string,
  'processedBy' : [] | [Principal],
  'processedDate' : [] | [Time],
  'amount' : bigint,
  'requestDate' : Time,
  'associate' : Principal,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'category' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'status' : string,
  'referralCode' : string,
  'joinDate' : Time,
  'name' : string,
  'email' : string,
  'referredBy' : [] | [Principal],
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[string, string, bigint, string], Product>,
  'getAllPayoutRequests' : ActorMethod<[], Array<PayoutRequest>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDirectReferrals' : ActorMethod<[], Array<Principal>>,
  'getDownlineStructure' : ActorMethod<
    [],
    {
      'level1Count' : bigint,
      'level2Count' : bigint,
      'level1' : Array<Principal>,
      'level2' : Array<Principal>,
    }
  >,
  'getEarningsDashboard' : ActorMethod<
    [],
    {
      'balance' : bigint,
      'totalEarned' : bigint,
      'commissionHistory' : Array<Commission>,
      'totalWithdrawn' : bigint,
    }
  >,
  'getMyPayoutRequests' : ActorMethod<[], Array<PayoutRequest>>,
  'getOrderHistory' : ActorMethod<[Principal], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderDelivered' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<[bigint, bigint], Order>,
  'processPayoutRequest' : ActorMethod<[bigint, boolean], undefined>,
  'registerWithReferral' : ActorMethod<[UserProfile, string], undefined>,
  'requestPayout' : ActorMethod<[bigint], PayoutRequest>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string],
    Product
  >,
  'updateWalletBalance' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];