/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const PayoutRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'processedBy' : IDL.Opt(IDL.Principal),
  'processedDate' : IDL.Opt(Time),
  'amount' : IDL.Nat,
  'requestDate' : Time,
  'associate' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'status' : IDL.Text,
  'referralCode' : IDL.Text,
  'joinDate' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Principal),
  'phone' : IDL.Text,
});
export const Commission = IDL.Record({
  'id' : IDL.Nat,
  'level' : IDL.Nat,
  'orderId' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'associate' : IDL.Principal,
});
export const FixedReferralBonusSummary = IDL.Record({
  'level6Count' : IDL.Nat,
  'level1Count' : IDL.Nat,
  'totalLevel3Amount' : IDL.Nat,
  'level4Count' : IDL.Nat,
  'totalLevel4Amount' : IDL.Nat,
  'lastUpdated' : Time,
  'totalLevel5Amount' : IDL.Nat,
  'level7Count' : IDL.Nat,
  'level2Count' : IDL.Nat,
  'totalLevel6Amount' : IDL.Nat,
  'totalBonuses' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'level5Count' : IDL.Nat,
  'totalLevel7Amount' : IDL.Nat,
  'totalLevel1Amount' : IDL.Nat,
  'level3Count' : IDL.Nat,
  'totalLevel2Amount' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'orderDate' : Time,
  'productId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'associate' : IDL.Principal,
});
export const ReferralBonus = IDL.Record({
  'id' : IDL.Nat,
  'level' : IDL.Nat,
  'referralBy' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'associate' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Product],
      [],
    ),
  'designateIdProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllPayoutRequests' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDirectReferrals' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getDownlineStructure' : IDL.Func(
      [],
      [
        IDL.Record({
          'level1Count' : IDL.Nat,
          'level2Count' : IDL.Nat,
          'level1' : IDL.Vec(IDL.Principal),
          'level2' : IDL.Vec(IDL.Principal),
        }),
      ],
      ['query'],
    ),
  'getEarningsDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'balance' : IDL.Nat,
          'totalEarned' : IDL.Nat,
          'commissionHistory' : IDL.Vec(Commission),
          'totalWithdrawn' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFixedReferralBonusSummary' : IDL.Func(
      [],
      [FixedReferralBonusSummary],
      ['query'],
    ),
  'getIdProducts' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getMyPayoutRequests' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
  'getOrderHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReferralBonusHistory' : IDL.Func([], [IDL.Vec(ReferralBonus)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderDelivered' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat], [Order], []),
  'processPayoutRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'registerWithReferral' : IDL.Func([UserProfile, IDL.Text], [], []),
  'removeIdProduct' : IDL.Func([IDL.Nat], [], []),
  'requestPayout' : IDL.Func([IDL.Nat], [PayoutRequest], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Product],
      [],
    ),
  'updateWalletBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PayoutRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'processedBy' : IDL.Opt(IDL.Principal),
    'processedDate' : IDL.Opt(Time),
    'amount' : IDL.Nat,
    'requestDate' : Time,
    'associate' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'status' : IDL.Text,
    'referralCode' : IDL.Text,
    'joinDate' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Principal),
    'phone' : IDL.Text,
  });
  const Commission = IDL.Record({
    'id' : IDL.Nat,
    'level' : IDL.Nat,
    'orderId' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'associate' : IDL.Principal,
  });
  const FixedReferralBonusSummary = IDL.Record({
    'level6Count' : IDL.Nat,
    'level1Count' : IDL.Nat,
    'totalLevel3Amount' : IDL.Nat,
    'level4Count' : IDL.Nat,
    'totalLevel4Amount' : IDL.Nat,
    'lastUpdated' : Time,
    'totalLevel5Amount' : IDL.Nat,
    'level7Count' : IDL.Nat,
    'level2Count' : IDL.Nat,
    'totalLevel6Amount' : IDL.Nat,
    'totalBonuses' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'level5Count' : IDL.Nat,
    'totalLevel7Amount' : IDL.Nat,
    'totalLevel1Amount' : IDL.Nat,
    'level3Count' : IDL.Nat,
    'totalLevel2Amount' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'orderDate' : Time,
    'productId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'associate' : IDL.Principal,
  });
  const ReferralBonus = IDL.Record({
    'id' : IDL.Nat,
    'level' : IDL.Nat,
    'referralBy' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'associate' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Product],
        [],
      ),
    'designateIdProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllPayoutRequests' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDirectReferrals' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getDownlineStructure' : IDL.Func(
        [],
        [
          IDL.Record({
            'level1Count' : IDL.Nat,
            'level2Count' : IDL.Nat,
            'level1' : IDL.Vec(IDL.Principal),
            'level2' : IDL.Vec(IDL.Principal),
          }),
        ],
        ['query'],
      ),
    'getEarningsDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'balance' : IDL.Nat,
            'totalEarned' : IDL.Nat,
            'commissionHistory' : IDL.Vec(Commission),
            'totalWithdrawn' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFixedReferralBonusSummary' : IDL.Func(
        [],
        [FixedReferralBonusSummary],
        ['query'],
      ),
    'getIdProducts' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getMyPayoutRequests' : IDL.Func([], [IDL.Vec(PayoutRequest)], ['query']),
    'getOrderHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReferralBonusHistory' : IDL.Func(
        [],
        [IDL.Vec(ReferralBonus)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderDelivered' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat], [Order], []),
    'processPayoutRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'registerWithReferral' : IDL.Func([UserProfile, IDL.Text], [], []),
    'removeIdProduct' : IDL.Func([IDL.Nat], [], []),
    'requestPayout' : IDL.Func([IDL.Nat], [PayoutRequest], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Product],
        [],
      ),
    'updateWalletBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };